PROMPT Creating synonyms for &&fmwk_home packages...
CREATE SYNONYM API_APP_LOG FOR &&fmwk_home.API_APP_LOG;
CREATE SYNONYM CNST FOR &&fmwk_home.CNST;
CREATE SYNONYM DT FOR &&fmwk_home.DT;
CREATE SYNONYM ENV FOR &&fmwk_home.ENV;
CREATE SYNONYM EXCP FOR &&fmwk_home.EXCP;
CREATE SYNONYM IO FOR &&fmwk_home.IO;
CREATE SYNONYM LOGS FOR &&fmwk_home.LOGS;
CREATE SYNONYM MAIL FOR &&fmwk_home.MAIL;
CREATE SYNONYM MSGS FOR &&fmwk_home.MSGS;
CREATE SYNONYM NUM FOR &&fmwk_home.NUM;
CREATE SYNONYM PARM FOR &&fmwk_home.PARM;
CREATE SYNONYM STR FOR &&fmwk_home.STR;
CREATE SYNONYM TYP FOR &&fmwk_home.TYP;
CREATE SYNONYM TIMER FOR &&fmwk_home.TIMER;
CREATE SYNONYM UTIL FOR &&fmwk_home.UTIL;

PROMPT Creating synonyms for &&fmwk_home sequences...
CREATE SYNONYM APP_CHG_LOG_SEQ FOR &&fmwk_home.APP_CHG_LOG_SEQ;
CREATE SYNONYM APP_DB_SEQ FOR &&fmwk_home.APP_DB_SEQ;
CREATE SYNONYM APP_EMAIL_DOC_SEQ FOR &&fmwk_home.APP_EMAIL_DOC_SEQ;
CREATE SYNONYM APP_EMAIL_SEQ FOR &&fmwk_home.APP_EMAIL_SEQ;
CREATE SYNONYM APP_ENV_SEQ FOR &&fmwk_home.APP_ENV_SEQ;
CREATE SYNONYM APP_LOCK_SEQ FOR &&fmwk_home.APP_LOCK_SEQ;
CREATE SYNONYM APP_LOG_SEQ FOR &&fmwk_home.APP_LOG_SEQ;
CREATE SYNONYM APP_MSG_SEQ FOR &&fmwk_home.APP_MSG_SEQ;
CREATE SYNONYM APP_PARM_SEQ FOR &&fmwk_home.APP_PARM_SEQ;
CREATE SYNONYM APP_SEQ FOR &&fmwk_home.APP_SEQ;
CREATE SYNONYM SEC_PMSN_SEQ FOR &&fmwk_home.SEC_PMSN_SEQ;
CREATE SYNONYM SEC_ROLE_SEQ FOR &&fmwk_home.SEC_ROLE_SEQ;
CREATE SYNONYM SEC_USER_SEQ FOR &&fmwk_home.SEC_USER_SEQ;

PROMPT Creating synonyms for &&fmwk_home tables...
CREATE SYNONYM APP FOR &&fmwk_home.APP;
CREATE SYNONYM APP_CHG_LOG FOR &&fmwk_home.APP_CHG_LOG;
CREATE SYNONYM APP_CHG_LOG_DTL FOR &&fmwk_home.APP_CHG_LOG_DTL;
CREATE SYNONYM APP_DB FOR &&fmwk_home.APP_DB;
CREATE SYNONYM APP_EMAIL FOR &&fmwk_home.APP_EMAIL;
CREATE SYNONYM APP_EMAIL_DOC FOR &&fmwk_home.APP_EMAIL_DOC;
CREATE SYNONYM APP_ENV FOR &&fmwk_home.APP_ENV;
CREATE SYNONYM APP_ENV_PARM FOR &&fmwk_home.APP_ENV_PARM;
CREATE SYNONYM APP_LOG FOR &&fmwk_home.APP_LOG;
CREATE SYNONYM APP_MSG FOR &&fmwk_home.APP_MSG;
CREATE SYNONYM APP_PARM FOR &&fmwk_home.APP_PARM;
CREATE SYNONYM SEC_ROLE FOR &&fmwk_home.SEC_ROLE;
CREATE SYNONYM SEC_ROLE_PMSN FOR &&fmwk_home.SEC_ROLE_PMSN;
CREATE SYNONYM SEC_USER FOR &&fmwk_home.SEC_USER;
CREATE SYNONYM SEC_USER_APP FOR &&fmwk_home.SEC_USER_APP;
CREATE SYNONYM SEC_USER_ROLE FOR &&fmwk_home.SEC_USER_ROLE;

PROMPT Creating synonyms for &&fmwk_home types...
CREATE SYNONYM TYPE_NTAB FOR &&fmwk_home.TYPE_NTAB;
CREATE SYNONYM TYPE_STAB FOR &&fmwk_home.TYPE_STAB;

PROMPT Creating synonyms for &&fmwk_home views...
CREATE SYNONYM APP_VW FOR &&fmwk_home.APP_VW;
CREATE SYNONYM APP_ENV_VW FOR &&fmwk_home.APP_ENV_VW;
CREATE SYNONYM APP_ENV_PARM_VW FOR &&fmwk_home.APP_ENV_PARM_VW;
CREATE SYNONYM APP_PARM_VW FOR &&fmwk_home.APP_PARM_VW;
CREATE SYNONYM SEC_PMSN_VW FOR &&fmwk_home.SEC_PMSN_VW;
CREATE SYNONYM SEC_ROLE_VW FOR &&fmwk_home.SEC_ROLE_VW;
CREATE SYNONYM SEC_ROLE_PMSN_VW FOR &&fmwk_home.SEC_ROLE_PMSN_VW;
CREATE SYNONYM SEC_USER_APP_VW FOR &&fmwk_home.SEC_USER_APP_VW;
CREATE SYNONYM SEC_USER_ROLE_VW FOR &&fmwk_home.SEC_USER_ROLE_VW;
